# Generated by Django 3.1.1 on 2020-09-17 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1500)),
                ('from_by', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.UUID('4a9881bc-ba76-45ee-87e0-c63ca1a4bb3f'), unique=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sentence.sentencetype')),
                ('update_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
