# Generated by Django 3.1.1 on 2020-09-17 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sentence', '0002_auto_20200917_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1500)),
                ('from_by', models.CharField(max_length=50)),
                ('creator', models.CharField(max_length=50)),
                ('uuid', models.UUIDField(default=uuid.UUID('678d395e-8338-45cc-a40b-d66188f18ba9'), unique=True)),
                ('create_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sentence_content',
            },
        ),
        migrations.RenameModel(
            old_name='SentenceType',
            new_name='ContentType',
        ),
        migrations.AlterModelTable(
            name='contenttype',
            table='sentence_content_type',
        ),
        migrations.DeleteModel(
            name='SentenceContent',
        ),
        migrations.AddField(
            model_name='content',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sentence.contenttype'),
        ),
        migrations.AddField(
            model_name='content',
            name='update_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
