# Generated by Django 3.1.1 on 2020-10-13 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0004_auto_20200917_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttype',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.CharField(max_length=1500, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='content',
            name='creator',
            field=models.CharField(max_length=50, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='content',
            name='from_by',
            field=models.CharField(max_length=50, null=True, verbose_name='出自哪里'),
        ),
        migrations.AlterField(
            model_name='content',
            name='from_who',
            field=models.CharField(max_length=50, null=True, verbose_name='出自谁'),
        ),
        migrations.AlterField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9029d98b-2df6-4497-86d1-5b1ebfdf9392'), unique=True),
        ),
    ]
