# Generated by Django 3.1.2 on 2020-10-30 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sentence', '0005_auto_20201013_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('717a5ebc-b404-4d55-a84e-50e8be8ace78'), unique=True),
        ),
    ]
